# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'foodHub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for foodHub
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  target 'foodHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'foodHubUITests' do
    # Pods for testing
  end

end
